### ISSUE TITLE
`.gitignore` im Root löschen?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/github-workflows#1]
Ist mir gerade nur nebenbei aufgefallen. Man könnte die Datei womöglich löschen zur besseren Übersicht. Und auch die gitignores in den Unterordnern sollten zum besseren Verständnis besser nur genau das enthalten, was für das Projekt notwendig ist.

Das Ignorieren von typischen Ressourcen wie System, IDEs, etc. bleibt normalerweise den Devs überlassen, die sich dafür eine gitignore auf höherer Ebene anlegen, die sich nach unten hin vererbt.

**Comment by eaCe** [comment]
Klar, dann muss ich nur aufpassen das ich meine .idea Ordner nicht committe :)

**Comment by eaCe** [comment]
Hm, die vendoren dann auch?

**Comment by schuer** [comment]
Die Vendoren sollte man vermutlich ignorieren. Die will man nicht im Git haben.
