### ISSUE TITLE
Standard - JavaScript Standard Style hinzufügen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/github-workflows#9]
**Feature description / Feature Beschreibung**
https://standardjs.com/#install

**Comment by eaCe** [comment]
https://github.com/standard/semistandard

**Comment by bloep** [comment]
oder vielleicht auch https://github.com/prettier/prettier

**Comment by eaCe** [comment]
Bei Standard hat man halt gleich Linter und Code Style. Bei Prettier bräcuhte man noch einen Linter

**Comment by eaCe** [comment]
Ich mach hier mal zu, das Interesse ist anderer ist sowieso nicht da.
